### ISSUE TITLE
Addition to Config dependency for netstandard

### ISSUE THREAD

**Issue by phandcock** [LeversonCarlos/Xamarin.OneDrive.Connector#13]
Hi

nice to see someone has a way to use OneDrive

I tried to run the follow the instructions and code on Xamarin but I had to add:

         if (!string.IsNullOrEmpty(_redirectUrl)) {
            configs.RedirectUri = _redirectUrl;
         }
         else {
            configs.RedirectUri = $"msal{configs.ClientID}://auth";
         }

to the Initialize function of the Dependency.netstandard.cs file to get it to work

Have I misunderstood something? Should I ask this somewhere else?  Is there another way to set the RedirectUri?

regards
Paul

**Comment by LeversonCarlos** [comment]
Hi there and sorry for this huge delay... I hadnt use the `netstandard` build. I had keep that to evolve a working test project. But get stucked couse the authentication process requires a interactive execution, that will not quite work on a test project.
So, i keeped netsatndard build, but i realy only use the android build (not even the iOS one, as i dont have devices).
So... you using the `netstandard` build for what reasons ? What do you need ?
