### ISSUE TITLE
Xamarin Forms, Onedrive not working in iOS but working on Android and UWP

### ISSUE THREAD

**Issue by marcdieters** [LeversonCarlos/Xamarin.OneDrive.Connector#15]
I hope can someone can help me with setting up connecting to OneDrive form a Xamarin Forms App.
I know there are lot of examples that can be found but these seem to be outdated. None of them work anymore.

Therefore I tried Xamarin.OneDrive which works on UWP and Android but not on iOS.

The steps I took on iOS:

    Added 'com.microsoft.adalcache' to the keychain group in Entitlements.plist

    Added the following code in appdelegate.cs

        public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
            Xamarin.OneDrive.Connector.SetAuthenticationContinuationEventArgs(url);
            return true;
        }

    Added the following to plist.info with the correct Bundlename and Appid

    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLName</key>
            <string><BUNDLENAME></string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string><APPID></string>
            </array>
        </dict>
    </array>

    Under iOS Bundle Signing I selected Manual Provisioning and selected Entitlements.plist in Custom Entitlements

Run running the application on a simulator or on a physical device results in the following error being shown:
System.Exception: 'Internal Server Error
System.ArgumentNullException: Value cannot be null.
Parameter name: viewController
at Microsoft.Identity.Client.AcquireTokenInteractiveParameterBuilder.WithParentActivityOrWindow (UIKit.UIViewController viewController) [0x00003] in :0
at Xamarin.OneDrive.DependencyImplementation.GetAuthResult (Microsoft.Identity.Client.IPublicClientApplication client, Xamarin.OneDrive.Configs configs) [0x00093] in <702bbb93f52d451c89c8adacbd52d653>:0
at Xamarin.OneDrive.Token.AcquireAsync () [0x00091] in <702bbb93f52d451c89c8adacbd52d653>:0
at Xamarin.OneDrive.Token.ConnectAsync () [0x000f0] in <702bbb93f52d451c89c8adacbd52d653>:0
at Xamarin.OneDrive.ConnectorHandler.InnerConnectionHandlerAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00161] in <702bbb93f52d451c89c8adacbd52d653>:0 '

I don't have a clue how to continue.

Can someone tell me how to get this working on iOS ?

Thanks in advance !

**Comment by LeversonCarlos** [comment]
Sorry about that. I have no iOS device nor macbook to help you out. I will flag this issue with `help need`, and keep it open for a while.

**Comment by prom3theu5** [comment]
As far as I know - .WithParentActivityOrWindow (UIKit.UIViewController viewController) isn't required to be called in iOS. Only the Android Activity is required.

**Comment by fsdsabel** [comment]
I got it working by commenting out line 20 `.WithParentActivityOrWindow((UIKit.UIViewController)configs.UiParent)` in the file Dependency.ios.cs. However I had to upgrade Microsoft.Identity.Client to version 4.14.0, otherwise storing the tokens in the KeyChain would not work.
