### ISSUE TITLE
What about creating folders/files?

### ISSUE THREAD

**Issue by pkar70** [LeversonCarlos/Xamarin.OneDrive.Connector#17]
Is there any possibility to create new folder, or new file?

**Comment by LeversonCarlos** [comment]
Hi there... i hadn't need that for my own project [ComicsShelf](https://github.com/LeversonCarlos/ComicsShelf). If you could kindly enhance that, here are the [docs](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http). Thanks

**Comment by pkar70** [comment]
I tried, but it fails very strangely :(
